### ISSUE TITLE
Quelle URL latest pour des versions invalides

### ISSUE THREAD

**Issue by AntoineAugusti** [AntoineAugusti/schema-agg#2]
Hello,

Dans le cas d'un dépôt `org/name` avec les versions suivantes et la validitée associée :
- 0.2.0 : valide
- 0.3.0 : valide
- 0.4.0 : invalide

Questions :
- Doit-on avoir une URL du style `schema.data.gouv.fr/schemas/org/name/latest/schema.json` ? La dernière version publiée n'étant pas valide
- L'URL latest, si elle existe, doit-elle renvoyer vers la dernière version valide (la 0.3.0 là) ?

**Comment by AntoineAugusti** [comment]
cc @abulte

**Comment by abulte** [comment]
Je vote pour `0.3.0` aka dernière version valide publiée.
